Repository 9taetae9/sb01-monew-team2, pull requests merged in 2025-04, with the labels that each got.

#28 feat: Naver API 연동 및 테스트
  monew/.gitignore
  monew/build.gradle
  monew/src/main/java/com/codeit/team2/monew/config/WebClientConfig.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/dto/FetchCommand.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/dto/NaverArticleItemDto.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/dto/NaverArticleResponseDto.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/external/NaverNewsClient.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/external/NewsClient.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/mapper/ArticleMapper.java
  monew/src/main/resources/application.yaml
  monew/src/test/java/com/codeit/team2/monew/MonewApplicationTests.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/external/LiveNaverNewsClientTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/external/NaverNewsClientTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/mapper/ArticleMapperTest.java
  monew/src/test/resources/application-test-live.yml
Labels: feat

#25 feat: 프로젝트 전체 schema 정의
  monew/src/main/resources/application.yaml
  monew/src/main/resources/schema.sql
Labels: feat

#39 feat/#37/article-interest
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/entity/Article.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/controller/InterestController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/controller/InterestRegisterRequest.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/dto/InterestDto.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/entity/Interest.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/entity/Keyword.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/mapper/InterestMapper.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/repository/InterestRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/repository/KeywordRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/relation/entity/ArticleInterest.java
  monew/src/main/java/com/codeit/team2/monew/module/service/InterestService.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/interest/service/InterestServiceTest.java
Labels: feat

#38 feat: user create api
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/entity/Comment.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/entity/CommentLike.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/member/.gitkeep
  monew/src/main/java/com/codeit/team2/monew/module/domain/notification/entity/Notification.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/notification/service/NotificationService.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/notification/service/NotificationServiceImpl.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/subscription/entity/Subscription.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/controller/UserController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/dto/UserDto.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/dto/UserRegisterRequest.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/entity/User.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/mapper/UserMapper.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/repository/UserRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/service/UserService.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/service/UserServiceImpl.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/notification/NotificationServiceTDDTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/user/service/UserServiceImplTest.java
Labels: feat

#40 feat: user update, login api 구현
  monew/src/main/java/com/codeit/team2/monew/config/WebConfig.java
  monew/src/main/java/com/codeit/team2/monew/config/interceptor/LoginCheckInterceptor.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/controller/UserController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/dto/request/UserLoginRequest.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/dto/request/UserRegisterRequest.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/dto/request/UserUpdateRequest.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/dto/response/UserDto.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/entity/User.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/mapper/UserMapper.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/repository/UserRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/service/UserService.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/service/UserServiceImpl.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/user/service/UserServiceImplTest.java
Labels: feat

#42 Feat/#36/notification check 알림 확인
  monew/src/main/java/com/codeit/team2/monew/module/domain/notification/controller/NotificationController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/notification/entity/Notification.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/notification/repository/NotificationRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/notification/service/NotificationService.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/notification/service/NotificationServiceImpl.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/notification/service/NotificationServiceImplTest.java
Labels: feat

#33 feat: Naver News API Batch Processor, Writer 구현
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/batch/BatchArticleWriter.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/batch/KeywordToArticlesProcessor.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/repository/ArticleRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/entity/Keyword.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/batch/ArticleBatchItemReaderTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/batch/BatchArticleWriterTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/batch/KeywordToArticlesProcessorTest.java
Labels: feat

#48 feat: article batch process 구현
  monew/build.gradle
  monew/src/main/java/com/codeit/team2/monew/config/WebConfig.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/batch/ArticleBatchConfig.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/batch/ArticleBatchScheduler.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/batch/ArticleBatchTestController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/batch/BatchArticleWriter.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/batch/KeywordReaderConfig.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/batch/KeywordToArticlesProcessor.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/dto/ArticleInterestCreateCommand.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/entity/Article.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/mapper/ArticleMapper.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/repository/ArticleInterestRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/repository/ArticleRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/entity/Keyword.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/repository/InterestKeywordRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/relation/entity/ArticleInterest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/batch/ArticleBatchIntegrationTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/batch/BatchArticleWriterTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/batch/KeywordToArticlesProcessorTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/external/NaverNewsClientTest.java
  monew/src/test/resources/application-test.yml
  monew/src/test/resources/insert-keywords.sql
  monew/src/test/resources/schema-batch.sql
  monew/src/test/resources/schema.sql
Labels: feat

#50 feat: user delete(soft, hard) api
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/Test.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/controller/UserController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/entity/User.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/repository/UserRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/service/UserService.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/service/UserServiceImpl.java
  monew/src/main/resources/schema.sql
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/batch/BatchArticleWriterTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/batch/KeywordToArticlesProcessorTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/external/NaverNewsClientTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/user/service/UserServiceImplTest.java
Labels: feat

#52 feat/#31/comment-cud
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/.gitkeep
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/dto/CommentLikeDto.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/dto/CommentRegisterRequest.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/dto/CommentUpdateRequest.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/mapper/CommentMapper.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/repository/CommentRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/service/CommentService.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/service/CommentServiceImpl.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/batch/BatchArticleWriterTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/comment/service/CommentServiceImplTest.java
Labels: feat

#54 feat/#23/notification create #23
  monew/src/main/java/com/codeit/team2/monew/module/domain/notification/service/NotificationServiceImpl.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/subscription/repository/SubscriptionRepository.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/notification/service/NotificationServiceImplTest.java
Labels: feat

#59 feat : article api 구현
  monew/src/main/java/com/codeit/team2/monew/module/common/exception/GlobalExceptionHandler.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/batch/ArticleBatchConfig.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/batch/BatchArticleWriter.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/batch/KeywordToArticlesProcessor.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/controller/ArticleController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/entity/Article.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/entity/ArticleView.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/external/NaverNewsClient.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/mapper/ArticleMapper.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/repository/ArticleViewRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/service/ArticleService.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/service/ArticleServiceImpl.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/relation/entity/ArticleInterest.java
  monew/src/main/resources/schema.sql
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/controller/ArticleControllerTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/service/ArticleServiceTest.java
Labels: feat

#66 feat: 알림 삭제 배치 기능 #55
  monew/src/main/java/com/codeit/team2/monew/MonewApplication.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/notification/batch/NotificationBatchConfig.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/notification/batch/NotificationScheduler.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/notification/repository/NotificationRepository.java
  monew/src/main/resources/application.yaml
Labels: feat

#61 [Feat]: 댓글 좋아요 관리 컨트롤러 구현 물리 삭제 api 추가
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/controller/CommentController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/controller/CommentLikeController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/service/CommentService.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/service/CommentServiceImpl.java
Labels: feat

#67 [Chore]: ci 워크플로우 구축
  .github/workflows/ci.yml
  .github/workflows/codecov.yml
  monew/build.gradle
  monew/src/main/resources/application-dev.yaml
  monew/src/main/resources/schema.sql
Labels: chore

#69 [Refactor]: 테스트 코드 수정
  .github/workflows/ci.yml
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/batch/ArticleBatchIntegrationTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/interest/repository/InterestRepositoryTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/interest/service/InterestServiceIntegrationTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/notification/service/NotificationServiceImplTest.java
Labels: refactor

#73 feat: BatchArticleWriter 성능 개선, HankyungRSS Client 구현
  monew/build.gradle
  monew/src/main/java/com/codeit/team2/monew/config/WebClientConfig.java
  monew/src/main/java/com/codeit/team2/monew/config/WebConfig.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/batch/ArticleBatchTestController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/batch/BatchArticleWriter.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/batch/KeywordToArticlesProcessor.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/controller/ArticleController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/dto/rss/HankyungRss.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/external/ApiNewsClient.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/external/HankyungApiNewsClient.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/external/HankyungNewsUrlProvider.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/external/NaverApiNewsClient.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/external/NewsUrlProvider.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/mapper/ArticleMapper.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/batch/ArticleBatchIntegrationTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/batch/BatchArticleWriterTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/batch/KeywordToArticlesProcessorTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/external/HankyungApiNewsClientTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/external/LiveNaverApiNewsClientTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/external/NaverApiNewsClientTest.java
  monew/src/test/resources/application-test-postgre.yml
  monew/src/test/resources/schema-batch-postgres.sql
Labels: feat

#79 feat/#68/notification read
  monew/src/main/java/com/codeit/team2/monew/module/domain/notification/controller/NotificationController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/notification/dto/CursorPageResponseNotificationDto.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/notification/mapper/NotificationMapper.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/notification/repository/NotificationRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/notification/service/NotificationService.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/notification/service/NotificationServiceImpl.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/notification/controller/NotificationControllerTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/notification/service/NotificationServiceImplTest.java
Labels: feat

#84 feat : 연합뉴스, 조선뉴스 RSS
  monew/src/main/java/com/codeit/team2/monew/config/WebClientConfig.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/batch/ArticleBatchTestController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/dto/rss/ChosunRss.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/dto/rss/YonhapRss.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/entity/Article.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/external/ChosunRssNewsClient.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/external/HankyungRssNewsClient.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/external/RssNewsClient.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/external/YonhapRssNewsClient.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/external/url_provider/ChosunNewsUrlProvider.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/external/url_provider/HankyungNewsUrlProvider.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/external/url_provider/NewsUrlProvider.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/external/url_provider/YonhapNewsUrlProvider.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/mapper/ArticleMapper.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/batch/ArticleBatchIntegrationTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/batch/BatchArticleWriterTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/batch/KeywordToArticlesProcessorTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/external/ChosunRssNewsClientTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/external/HankyungRssNewsClientTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/external/NaverApiNewsClientTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/external/YonhapRssNewsClientTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/rss/ChosunRssTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/service/ArticleServiceTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/useractivity/service/UserActivityServiceImplTest.java
Labels: feat

#86 feat: 알림 생성 기능 #83
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/batch/BatchArticleWriter.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/service/CommentLikeServiceImpl.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/notification/service/NotificationService.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/notification/service/NotificationServiceImpl.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/batch/BatchArticleWriterTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/comment/service/CommentLikeServiceImplTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/notification/service/NotificationServiceImplTest.java
Labels: feat

#88 feat: mongodb 연동 및 관련 Document 정의
  monew/build.gradle
  monew/src/main/java/com/codeit/team2/monew/config/MongoDbConfig.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/repository/ArticleViewRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/repository/CommentLikeRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/repository/CommentRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/TestDataInitializer.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/event/RegisterUserEvent.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/service/UserServiceImpl.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/useractivity/document/ArticleViewItem.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/useractivity/document/CommentItem.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/useractivity/document/CommentLikeItem.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/useractivity/document/SubscriptionItem.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/useractivity/document/UserActivity.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/useractivity/dto/ArticleViewItemDto.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/useractivity/dto/CommentItemDto.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/useractivity/dto/CommentLikeItemDto.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/useractivity/dto/SubscriptionItemDto.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/useractivity/dto/UserActivityDto.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/useractivity/listener/UserEventListener.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/useractivity/mapper/UserActivityMapper.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/useractivity/repository/MongoUserActivityRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/useractivity/service/MongoUserActivityService.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/useractivity/service/UserActivityServiceImpl.java
  monew/src/main/resources/application-dev.yaml
  monew/src/main/resources/application.yaml
  monew/src/test/java/com/codeit/team2/monew/module/domain/user/service/UserServiceImplTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/useractivity/service/MongoUserActivityServiceTest.java
Labels: feat

#93 Feat/#87/article read
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/controller/ArticleController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/dto/ArticleDto.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/dto/CursorPageResponseArticleDto.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/dto/request/ArticleFindRequest.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/dto/request/ArticleOrderBy.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/dto/request/ArticleSourceIn.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/repository/ArticleCustomRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/repository/ArticleCustomRepositoryImpl.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/repository/ArticleViewRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/service/ArticleService.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/service/ArticleServiceImpl.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/service/ArticleServiceTest.java
Labels: feat

#95 feat: 프론트에 맞춰 기사 목록 조회 자료형 수정 #94
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/controller/ArticleController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/dto/request/CursorPageRequestArticleDto.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/service/ArticleService.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/service/ArticleServiceImpl.java
  monew/src/main/resources/application.yaml
Labels: feat

#98 [Feat]: 기사 백업 및 복구 api 구현
  monew/build.gradle
  monew/src/main/java/com/codeit/team2/monew/module/domain/BaseEntity.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/backup/batch/ArticleBackupConfig.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/backup/batch/ArticleBackupProcessor.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/backup/batch/ArticleBackupReaderConfig.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/backup/batch/ArticleBackupWriter.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/backup/batch/S3Config.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/backup/controller/ArticleBackupTestController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/backup/controller/ArticleRestoreController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/backup/dto/ArticleBackupDto.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/backup/dto/ArticleRestoreResultDto.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/backup/scheduler/ArticleBackupScheduler.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/backup/service/ArticleRestoreService.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/mapper/ArticleMapper.java
  monew/src/main/resources/application-dev.yaml
  monew/src/main/resources/application.yaml
  monew/src/test/resources/application-test-postgre.yml
Labels: feat

#104 Feat/#78/interest list
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/controller/InterestController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/dto/request/CursorPageRequestInterestDto.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/dto/request/InterestOrderBy.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/dto/response/CursorPageResponseInterestDto.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/repository/InterestCustomRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/repository/InterestCustomRepositoryImpl.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/service/InterestService.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/service/InterestServiceImpl.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/interest/service/InterestServiceImplTest.java
Labels: feat

#106 Task/#97/swagger write
  monew/src/main/java/com/codeit/team2/monew/config/SwaggerConfig.java
  monew/src/main/java/com/codeit/team2/monew/config/SwaggerTags.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/backup/controller/ArticleRestoreController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/backup/controller/docs/ArticleRestoreControllerDocs.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/controller/ArticleController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/controller/docs/ArticleControllerDocs.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/controller/CommentController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/controller/CommentLikeController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/controller/docs/CommentControllerDocs.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/controller/docs/CommentLikeControllerDocs.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/controller/InterestController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/controller/docs/InterestControllerDocs.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/notification/controller/NotificationController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/notification/controller/docs/NotificationControllerDocs.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/controller/UserController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/controller/docs/UserControllerDocs.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/useractivity/controller/UserActivityController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/useractivity/controller/docs/UserActivityControllerDocs.java
  monew/src/main/resources/application.yaml
Labels: chore

#107 [Refactor]: 복구 서비스 - 트랜잭션 처리 개선
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/backup/controller/ArticleRestoreController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/backup/service/ArticleRestoreService.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/backup/service/ArticleRestoreTransactionService.java
Labels: refactor

#112 feat: Dockerfile, CD script, task-definition.json 정의
  .github/workflows/deploy.yml
  .github/workflows/ecs/task-definition.json
  monew/Dockerfile
  monew/src/main/resources/application-prod.yaml
  monew/src/main/resources/application.yaml
Labels: chore

#115 Feat/#100/comment read
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/controller/CommentController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/controller/docs/CommentControllerDocs.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/dto/CommentOrderBy.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/dto/CursorPageRequestCommentDto.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/dto/CursorPageResponseCommentDto.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/repository/CommentCustomRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/repository/CommentCustomRepositoryImpl.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/repository/CommentRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/service/CommentService.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/service/CommentServiceImpl.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/comment/service/CommentServiceImplTest.java
Labels: feat

#117 [feat]: 새로고침, 뒤로가기 문제 해결을 위한 설정 추가
  monew/src/main/java/com/codeit/team2/monew/config/WebConfig.java
Labels: feat

#124 [Hotfix]: 설정 수정 2
  monew/src/main/java/com/codeit/team2/monew/config/WebConfig.java
  monew/src/main/resources/static/assets/index-DF13B-h9.js
Labels: hotfix

#123 [Release] v1.0.0
  monew/src/main/java/com/codeit/team2/monew/config/WebConfig.java
  monew/src/main/resources/static/assets/index-DF13B-h9.js
Labels: hotfix

#126 [hotfix]: 댓글 수정 오류 해결
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/controller/CommentController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/service/CommentService.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/service/CommentServiceImpl.java
  monew/src/main/resources/application-prod.yaml
  monew/src/test/java/com/codeit/team2/monew/module/domain/comment/service/CommentServiceImplTest.java
Labels: hotfix

#132 [Chore]: t2.micro 환경에서 OOM 이슈 관련 설정 수정 및 버전 자동화 구현, EC2 스왑 영역 설정
  .github/workflows/deploy.yml
  .github/workflows/ecs/task-definition.json
  monew/Dockerfile
  monew/build.gradle
Labels: chore

#133 [Chore] swagger json 추출 플러그인 추가 및 api 문서 추가
  monew/build.gradle
  monew/docs/api/swagger-v1.0.0.json
Labels: chore

#136 feat: 활동 내역 관리 - 등록
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/backup/batch/ArticleBackupProcessor.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/backup/batch/ArticleBackupReaderConfig.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/backup/controller/ArticleBackupTestController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/backup/controller/ArticleRestoreController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/backup/scheduler/ArticleBackupScheduler.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/dto/ArticleDto.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/dto/ArticleViewDto.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/dto/CursorPageResponseArticleDto.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/event/ArticleViewCreateEvent.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/service/ArticleServiceImpl.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/dto/CommentDto.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/dto/CommentLikeDto.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/dto/CommentRegisterRequest.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/event/CommentLikeRegisterEvent.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/event/CommentRegisterEvent.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/service/CommentLikeServiceImpl.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/service/CommentServiceImpl.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/dto/request/CursorPageRequestInterestDto.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/subscription/event/SubscriptionRegisterEvent.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/subscription/service/SubscriptionServiceImpl.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/TestDataInitializer.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/useractivity/document/CommentItem.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/useractivity/document/UserActivity.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/useractivity/listener/ArticleEventListener.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/useractivity/listener/CommentEventListener.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/useractivity/listener/SubscriptionEventListener.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/useractivity/repository/MongoCommentItemRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/useractivity/service/MongoUserActivityService.java
  monew/src/main/resources/application-dev.yaml
  monew/src/test/java/com/codeit/team2/monew/module/TestEntityFactory.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/service/ArticleServiceTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/comment/service/CommentLikeServiceImplTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/comment/service/CommentServiceImplTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/subscription/service/SubscriptionServiceImplTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/useractivity/service/MongoUserActivityServiceTest.java
Labels: feat

#141 feat : Article Batch 성능 개선
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/batch/ArticleBatchScheduler.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/batch/ArticleBatchTestController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/batch/BatchArticleWriter.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/batch/KeywordToArticlesProcessor.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/batch/rss/KeywordCache.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/repository/ArticleInterestRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/repository/InterestKeywordRepository.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/batch/KeywordToArticlesProcessorTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/batch/rss/KeywordCacheTest.java
Labels: refactor

#138 Feat: 예외 및 공통 응답 구현
  monew/src/main/java/com/codeit/team2/monew/module/common/exception/BaseException.java
  monew/src/main/java/com/codeit/team2/monew/module/common/exception/CommonErrorCode.java
  monew/src/main/java/com/codeit/team2/monew/module/common/exception/ErrorCode.java
  monew/src/main/java/com/codeit/team2/monew/module/common/exception/ErrorResponse.java
  monew/src/main/java/com/codeit/team2/monew/module/common/exception/GlobalExceptionHandler.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/code/InterestErrorCode.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/dto/request/InterestRegisterRequest.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/exception/InterestNotFoundException.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/service/InterestServiceImpl.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/interest/controller/InterestControllerTest.java
Labels: feat

#139 Feat/#130/article read refactor #130
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/mapper/ArticleMapper.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/repository/ArticleCustomRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/repository/ArticleCustomRepositoryImpl.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/repository/ArticleRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/repository/ArticleViewRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/service/ArticleServiceImpl.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/repository/CommentRepository.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/controller/ArticleControllerTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/service/ArticleServiceTest.java
Labels: refactor

#149 Feat/#145/notf read refactor 알림 조회 리팩토링, 테스트 커버리지
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/repository/CommentCustomRepositoryImpl.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/notification/controller/docs/NotificationControllerDocs.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/notification/dto/CursorPageResponseNotificationDto.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/notification/repository/NotificationCustomRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/notification/repository/NotificationCustomRepositoryImpl.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/notification/repository/NotificationRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/notification/service/NotificationServiceImpl.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/notification/repository/NotificationCustomRepositoryImplTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/notification/repository/NotificationRepositoryTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/notification/service/NotificationServiceImplTest.java
Labels: refactor

#162 Feat/#151/interest read refactor
  monew/src/main/java/com/codeit/team2/monew/MonewApplication.java
  monew/src/main/java/com/codeit/team2/monew/config/ScheduleConfig.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/dto/request/CursorPageRequestInterestDto.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/dto/response/CursorPageResponseInterestDto.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/repository/InterestCustomRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/repository/InterestCustomRepositoryImpl.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/repository/InterestRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/service/InterestServiceImpl.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/subscription/repository/SubscriptionRepository.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/interest/repository/InterestCustomRepositoryTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/interest/service/InterestServiceImplTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/notification/repository/NotificationCustomRepositoryTest.java
Labels: refactor

#160 [Refactor]: comment test 코드 개선 및 커스텀 예외 추가
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/code/ArticleErrorCode.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/exception/ArticleNotFoundException.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/code/CommentErrorCode.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/exception/CommentInvalidRequestException.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/exception/CommentLikeAlreadyExistsException.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/exception/CommentLikeNotFoundException.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/exception/CommentNotFoundException.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/exception/CommentPermissionDeniedException.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/service/CommentLikeServiceImpl.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/service/CommentServiceImpl.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/code/UserErrorCode.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/exception/UserNotFoundException.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/comment/controller/CommentControllerTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/comment/controller/CommentLikeControllerTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/comment/entity/CommentEntityTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/comment/entity/CommentLikeEntityTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/comment/mapper/CommentMapperTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/comment/service/CommentLikeServiceImplTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/comment/service/CommentServiceImplTest.java
Labels: refactor
