Repository 9taetae9/sb01-monew-team2, pull requests merged in 2025-05, with the labels that each got.

#165 [Refactor] 댓글 목록 조회 리팩토링, 테스트 코드 추가
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/controller/docs/CommentControllerDocs.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/repository/CommentCustomRepositoryImpl.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/repository/CommentLikeRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/repository/CommentRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/service/CommentServiceImpl.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/comment/repository/CommentCustomRepositoryImplTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/comment/service/CommentServiceImplTest.java
Labels: refactor

#166 [Refactor] 백업 관련 리펙토링 및 커스텀 예외 추가
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/backup/batch/ArticleBackupConfig.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/backup/batch/ArticleBackupReaderConfig.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/backup/controller/ArticleBackupTestController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/backup/controller/ArticleRestoreController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/backup/exception/ArticleBackupErrorCode.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/backup/exception/ArticleBackupException.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/backup/service/ArticleRestoreService.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/backup/service/ArticleRestoreTransactionService.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/exception/ArticleErrorCode.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/exception/ArticleNotFoundException.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/exception/CommentErrorCode.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/exception/CommentInvalidRequestException.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/exception/CommentLikeAlreadyExistsException.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/exception/CommentLikeNotFoundException.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/exception/CommentNotFoundException.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/exception/CommentPermissionDeniedException.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/exception/InterestErrorCode.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/exception/InterestNotFoundException.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/exception/InvalidSimilarityInputException.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/exception/SimilarInterestAlreadyExistsException.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/subscription/exception/DuplicateSubscriptionException.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/subscription/exception/SubscriptionErrorCode.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/subscription/exception/SubscriptionNotFoundException.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/exception/UserErrorCode.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/exception/UserNotFoundException.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/interest/controller/InterestControllerTest.java
Labels: refactor

#172 [Refactor] 목록 조회 관련 기능 테스트 커버리지 개선
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/controller/docs/CommentControllerDocs.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/repository/ArticleCustomRepositoryImplTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/comment/repository/CommentCustomRepositoryImplTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/interest/controller/InterestControllerTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/interest/repository/InterestCustomRepositoryTest.java
Labels: refactor

#174 [Feat] Notification 커스텀 예외 추가
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/service/ArticleServiceImpl.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/comment/service/CommentServiceImpl.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/service/InterestServiceImpl.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/notification/exception/NotificationAccessDeniedException.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/notification/exception/NotificationErrorCode.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/notification/exception/NotificationNotFoundException.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/notification/service/NotificationServiceImpl.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/service/ArticleServiceTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/comment/service/CommentServiceImplTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/interest/service/InterestServiceImplTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/notification/service/NotificationServiceImplTest.java
Labels: feat

#178 [Feat]: MDC 기반 요청 추적 및 S3 로그 백업 구현 및 테스트 코드 작성
  .github/workflows/ci.yml
  monew/.gitignore
  monew/build.gradle
  monew/src/main/java/com/codeit/team2/monew/config/MDCFilter.java
  monew/src/main/java/com/codeit/team2/monew/config/TimeConfig.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/backup/scheduler/ArticleBackupScheduler.java
  monew/src/main/java/com/codeit/team2/monew/module/log/LogUploadController.java
  monew/src/main/java/com/codeit/team2/monew/module/log/LogUploadScheduler.java
  monew/src/main/java/com/codeit/team2/monew/module/log/LogUploadService.java
  monew/src/main/resources/application-prod.yaml
  monew/src/main/resources/application-test.yaml
  monew/src/main/resources/application.yaml
  monew/src/main/resources/logback-spring.xml
  monew/src/test/java/com/codeit/team2/monew/config/TimeConfigTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/backup/scheduler/ArticleBackupSchedulerTest.java
  monew/src/test/java/com/codeit/team2/monew/module/log/LogUploadControllerTest.java
  monew/src/test/java/com/codeit/team2/monew/module/log/LogUploadSchedulerTest.java
  monew/src/test/java/com/codeit/team2/monew/module/log/LogUploadServiceIntegrationTest.java
  monew/src/test/java/com/codeit/team2/monew/module/log/LogUploadServiceTest.java
Labels: feat

#179 refactor: user 도메인 커스텀 예외 적용 및 테스트 커버리지 개선
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/TestDataInitializer.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/exception/UserEmailAlreadyExistsException.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/exception/UserErrorCode.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/exception/UserNicknameAlreadyExistsException.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/exception/UserNotFoundException.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/exception/UserUnauthorizedException.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/user/service/UserServiceImpl.java
  monew/src/main/resources/application.yaml
  monew/src/test/java/com/codeit/team2/monew/module/domain/user/controller/UserControllerTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/user/service/UserServiceImplTest.java
Labels: refactor

#185 [Feat]: 백업 관련 테스트 코드 작성
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/backup/service/ArticleRestoreService.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/backup/batch/ArticleBackupProcessorTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/backup/batch/ArticleBackupWriterTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/backup/service/ArticleRestoreServiceTest.java
Labels: refactor

#186 [Chore] API 요청별 쿼리 실행 수, 총 실행 시간 로그
  monew/src/main/java/com/codeit/team2/monew/config/queryAspect/ConnectionProxyHandler.java
  monew/src/main/java/com/codeit/team2/monew/config/queryAspect/PreparedStatementProxyHandler.java
  monew/src/main/java/com/codeit/team2/monew/config/queryAspect/QueryStatistics.java
  monew/src/main/java/com/codeit/team2/monew/config/queryAspect/QueryStatisticsAop.java
Labels: chore

#192 task: api 문서 생성 워크플로우 수정
  .github/workflows/generate-openapi.yml
Labels: chore

#195 feat: 관심사 테스트 커버리지 개선
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/exception/InterestNotFoundException.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/service/InterestServiceImpl.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/subscription/service/SubscriptionServiceImpl.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/interest/controller/InterestControllerTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/interest/service/InterestNameSimilarityServiceTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/interest/service/InterestServiceImplTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/subscription/service/SubscriptionServiceImplTest.java
Labels: refactor

#202 [Hotfix]: logback 롤링 정책 및 시스템, jvm 레벨 타임존 설정 추가
  monew/Dockerfile
  monew/src/main/java/com/codeit/team2/monew/module/log/LogUploadScheduler.java
  monew/src/main/resources/logback-spring.xml
  monew/src/test/java/com/codeit/team2/monew/module/log/LogUploadSchedulerTest.java
Labels: hotfix

#206 [Refactor] 알림 삭제 배치 작업 스케줄, 타임존 조정
  monew/src/main/java/com/codeit/team2/monew/module/domain/notification/batch/NotificationScheduler.java
Labels: refactor

#211 [Refactor] t2.micro에서 t3.small로 인스턴스 유형 변경 및 메모리 최적화
  .github/workflows/deploy.yml
  .github/workflows/ecs/task-definition.json
  monew/Dockerfile
Labels: refactor

#213 [Hotfix] 메모리 설정 최적화
  .github/workflows/deploy.yml
  .github/workflows/ecs/task-definition.json
  monew/Dockerfile
Labels: hotfix

#214 [Release] v2.1.0 메모리 설정 수정
  .github/workflows/deploy.yml
  .github/workflows/ecs/task-definition.json
  monew/Dockerfile
Labels: hotfix

#216 chore: 변수 누락 수정
  monew/Dockerfile
Labels: chore

#219 [Release] v2.1.0 - HikariCP 최적화 설정
  monew/src/main/resources/application-prod.yaml
Labels: hotfix

#210 [Feat] Spring Actuator, Spring Boot Admin
  .github/workflows/deploy.yml
  .github/workflows/ecs/task-definition.json
  monew/admin/Dockerfile
  monew/admin/build.gradle
  monew/admin/gradle/wrapper/gradle-wrapper.jar
  monew/admin/gradle/wrapper/gradle-wrapper.properties
  monew/admin/src/main/java/com/sprint/mission/admin/AdminApplication.java
  monew/admin/src/main/resources/application.yaml
  monew/admin/src/test/java/com/sprint/mission/admin/AdminApplicationTests.java
  monew/build.gradle
  monew/settings.gradle
  monew/src/main/java/com/codeit/team2/monew/module/actuator/BatchMetrics.java
  monew/src/main/resources/application-dev.yaml
  monew/src/main/resources/application-prod.yaml
  monew/src/main/resources/application.yaml
  monew/src/test/java/com/codeit/team2/monew/module/actuator/BatchMetricsTest.java
Labels: feat

#222 Feat/#156/interest queries refactor
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/repository/InterestRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/repository/KeywordRepository.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/interest/service/InterestServiceImpl.java
  monew/src/main/resources/application-openapi.yaml
  monew/src/main/resources/schema.sql
  monew/src/test/java/com/codeit/team2/monew/module/domain/interest/repository/InterestRepositoryTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/interest/repository/KeywordRepositoryTest.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/interest/service/InterestServiceImplTest.java
Labels: refactor

#252 fix: BatchMetrics openapi 프로필에서 비활성화
  monew/src/main/java/com/codeit/team2/monew/module/actuator/BatchMetrics.java
Labels: hotfix

#256 feat: 기사 출처 목록 조회 api 구현
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/controller/ArticleController.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/controller/docs/ArticleControllerDocs.java
  monew/src/main/java/com/codeit/team2/monew/module/domain/article/dto/request/ArticleSourceIn.java
  monew/src/test/java/com/codeit/team2/monew/module/domain/article/controller/ArticleControllerTest.java
Labels: feat
